import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { Title } from '../components/Title'
import Form from '../components/Form'

export default function Home() {
  return (
    <div className={'container-fluid'}>
      <Head>
        <title>Marcio - Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title pageTitle={'Contact Form'} />
      <Form />
      <footer className={styles.footer}>
        <a
          href="https://marcio.vercel.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Marcio Iwamoto
        </a>
      </footer>
    </div>
  )
}